//! Provider registry — service providers wired into the app boot DAG.
//!
//! `bootstrap/app.rs::configure` consumes this registry, so providers
//! generated by `cargo artisan make:provider` are appended here. This mirrors
//! the kit's `AppServiceProvider::configureDefaults()`, which installs three
//! process-wide policies at boot:
//!
//! 1. A password policy (`Password::defaults()`), strict in production.
//! 2. A destructive-command guard (`DB::prohibitDestructiveCommands()`).
//! 3. Immutable dates (`Date::use(Illuminate\Support\CarbonImmutable::class)`).
//!
//! # Immutable dates — not applicable
//!
//! The kit pins every model attribute to an immutable date class because
//! Carbon's `now()` mutates in place. Rust's `chrono` has no global mutable
//! date default: [`chrono::DateTime`] is already an immutable value type and
//! `Utc::now()` returns a fresh value each call, so there is nothing to
//! override. The kit decision is therefore documented here as **not
//! applicable** rather than reproduced with an invented mechanism.

use rustasea::config::ConfigLoader;
use rustasea::validation::PasswordPolicy;
use rustasea::{Application, ServiceProvider};

use super::auth::{install_session_guard, SESSION_GUARD_KEY};

/// Container key holding the resolved environment name (`String`).
pub const ENVIRONMENT_KEY: &str = "app.environment";

/// Container key holding the installed [`PasswordPolicy`].
pub const PASSWORD_POLICY_KEY: &str = "app.password_policy";

/// Container key holding whether destructive commands are prohibited (`bool`).
pub const DESTRUCTIVE_COMMANDS_PROHIBITED_KEY: &str = "app.prohibits_destructive_commands";

/// Resolve the active application environment, highest precedence first.
///
/// Precedence:
/// 1. `APP_ENV` — plain process environment variable.
/// 2. The `app_env` key from `config/app.toml` (itself overlaid by `APP_ENV`).
/// 3. [`rustasea::orm::PRODUCTION`] — the fail-closed default, matching Laravel.
pub fn app_environment() -> String {
    if let Some(env) = std::env::var("APP_ENV")
        .ok()
        .map(|value| value.trim().to_string())
        .filter(|value| !value.is_empty())
    {
        return env;
    }
    if let Ok(loader) = ConfigLoader::load_from(&["config/app"]) {
        if let Ok(env) = loader.get_key::<String>("app_env") {
            let env = env.trim();
            if !env.is_empty() {
                return env.to_string();
            }
        }
    }
    rustasea::orm::PRODUCTION.to_string()
}

/// Whether destructive commands are prohibited for `environment`.
///
/// True only in production, mirroring the kit's
/// `DB::prohibitDestructiveCommands($this->app->isProduction())`.
pub fn prohibits_destructive_commands(environment: &str) -> bool {
    rustasea::orm::is_production(environment)
}

/// Select the password policy for `environment`.
///
/// Production gets [`PasswordPolicy::production`] (min 12, mixed case, letters,
/// numbers, symbols); every other environment gets [`PasswordPolicy::default`]
/// (min 12 only), matching the kit's relaxed local defaults.
pub fn password_policy_for(environment: &str) -> PasswordPolicy {
    if prohibits_destructive_commands(environment) {
        PasswordPolicy::production()
    } else {
        PasswordPolicy::default()
    }
}

/// Application service provider.
///
/// Installs the app-level policy defaults resolved from the environment into
/// the foundation container, mirroring the kit's
/// `AppServiceProvider::configureDefaults()`. Downstream code (routes, actions,
/// the CLI) resolves these bindings instead of re-deriving the policy.
pub struct AppServiceProvider;

impl ServiceProvider for AppServiceProvider {
    /// Stable provider name used for dependency resolution.
    fn name(&self) -> &'static str {
        "AppServiceProvider"
    }

    /// Resolve and install the environment-derived policy defaults.
    fn register(&self, app: &mut Application) {
        let environment = app_environment();
        let policy = password_policy_for(&environment);
        let prohibited = prohibits_destructive_commands(&environment);

        app.container.instance(ENVIRONMENT_KEY, environment.clone());
        app.container.instance(PASSWORD_POLICY_KEY, policy);
        app.container
            .instance(DESTRUCTIVE_COMMANDS_PROHIBITED_KEY, prohibited);

        println!(
            "app: environment `{environment}` (destructive commands {})",
            if prohibited { "prohibited" } else { "allowed" }
        );
    }

    /// Boot after all providers have registered.
    ///
    /// The defaults are pure container instances resolved during `register`,
    /// so no post-registration reconciliation is required.
    fn boot(&self, _app: &Application) {}
}

/// Auth service provider — the RustaSea analogue of `FortifyServiceProvider`.
///
/// During [`ServiceProvider::register`] it builds the real
/// [`rustasea::auth::SessionGuard`] from `config/session.toml` (see
/// [`super::auth::build_session_guard`]) and installs it into the foundation
/// container under [`SESSION_GUARD_KEY`]. `main`/tests resolve that binding to
/// seed [`AppState`](rustasea::http::AppState), and the `auth` route middleware
/// downcasts the installed guard to project `Extension<AuthUser>`.
///
/// # Fail-closed
///
/// The guard is built over the fail-closed `StaticLookup` (no database-backed
/// lookup exists yet), so no credential resolves and no login can succeed. A
/// missing/malformed `session.toml` leaves the container unbound: the app then
/// serves without an auth slot and the existing gates keep redirecting.
///
/// [`ServiceProvider::register`]: rustasea::ServiceProvider::register
pub struct AuthServiceProvider;

impl ServiceProvider for AuthServiceProvider {
    /// Stable provider name used for dependency resolution.
    fn name(&self) -> &'static str {
        "AuthServiceProvider"
    }

    /// Build and install the session guard into the container.
    fn register(&self, app: &mut Application) {
        if install_session_guard(&mut app.container) {
            println!("auth: session guard wired from config/session.toml");
        } else {
            eprintln!(
                "auth: no session guard installed; gated routes stay closed \
                 (container key {SESSION_GUARD_KEY:?} unbound)"
            );
        }
    }

    /// Boot after all providers have registered.
    ///
    /// Nothing to boot yet — the guard is a stateless shared `Arc`, so no
    /// post-registration reconciliation is required.
    fn boot(&self, _app: &Application) {}
}

/// Return the providers registered for the application boot DAG.
///
/// Order is the tie-breaker for providers without `dependencies()`; the
/// foundation [`Application::boot`] topologically sorts them regardless.
/// [`AuthServiceProvider`] runs after [`AppServiceProvider`] so app bindings are
/// in place before the auth wiring reads them.
pub fn providers() -> Vec<Box<dyn ServiceProvider>> {
    vec![Box::new(AppServiceProvider), Box::new(AuthServiceProvider)]
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    /// Serializes tests that read or write process-global environment variables.
    static ENV_LOCK: Mutex<()> = Mutex::new(());

    /// Run `body` with `APP_ENV` set to `value`, restoring the prior state.
    fn with_app_env<T>(value: &str, body: impl FnOnce() -> T) -> T {
        let previous = std::env::var("APP_ENV").ok();
        std::env::set_var("APP_ENV", value);
        let result = body();
        match previous {
            Some(previous) => std::env::set_var("APP_ENV", previous),
            None => std::env::remove_var("APP_ENV"),
        }
        result
    }

    /// Production gets the strict policy; non-production gets the relaxed one.
    #[test]
    fn password_policy_differs_by_environment() {
        assert_eq!(
            password_policy_for("production"),
            PasswordPolicy::production()
        );
        assert_ne!(password_policy_for("production"), PasswordPolicy::default());
        assert_eq!(password_policy_for("local"), PasswordPolicy::default());
    }

    /// Destructive commands are prohibited only in production.
    #[test]
    fn destructive_commands_are_prohibited_in_production_only() {
        assert!(prohibits_destructive_commands("production"));
        assert!(prohibits_destructive_commands("PRODUCTION"));
        assert!(!prohibits_destructive_commands("local"));
        assert!(!prohibits_destructive_commands("staging"));
    }

    /// An unset environment defaults to production (fail-closed).
    #[test]
    fn unset_environment_defaults_to_production() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let previous = std::env::var("APP_ENV").ok();
        std::env::remove_var("APP_ENV");
        assert_eq!(app_environment(), rustasea::orm::PRODUCTION);
        match previous {
            Some(previous) => std::env::set_var("APP_ENV", previous),
            None => std::env::remove_var("APP_ENV"),
        }
    }

    /// `APP_ENV` wins over the config file.
    #[test]
    fn app_env_variable_wins() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        with_app_env("local", || assert_eq!(app_environment(), "local"));
    }

    /// `register` installs all three policy defaults into the container.
    #[test]
    fn register_installs_policy_defaults() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        with_app_env("production", || {
            let mut app = Application::configure(|_| {});
            AppServiceProvider.register(&mut app);

            assert_eq!(
                app.container.get::<String>(ENVIRONMENT_KEY),
                Some(&"production".to_string())
            );
            assert_eq!(
                app.container.get::<PasswordPolicy>(PASSWORD_POLICY_KEY),
                Some(&PasswordPolicy::production())
            );
            assert_eq!(
                app.container
                    .get::<bool>(DESTRUCTIVE_COMMANDS_PROHIBITED_KEY),
                Some(&true)
            );
        });
    }
}
